# Generated by Django 4.1.2 on 2022-10-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('summary', models.TextField()),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('date', models.DateField()),
            ],
        ),
    ]
