version: "3"

services:

  backend:
    image: blog-b
    build: blog-django
    ports:
      - "8000:8000"

  frontend:
    image: blog-f
    build: blog-reactjs
    ports:
      - "8001:8001"
    depends_on:
      - backend
  

